---
version: 1.0.0

gateway:
  port: 3673
  hostname: localhost

registry:
  url: https://registry.director.run

playbooks:
  - id: test
    name: test
    prompts:
      - name: toilet
        title: the toilet prompt
        body: tell me the story of a man on the toilet
      - name: molly
        title: the molly prompt
        body: tell me about molly the mollywog 
    servers:
      - name: hackernews
        transport:
          type: stdio
          command: uvx
          args:
            - "--from"
            - git+https://github.com/erithwik/mcp-hn
            - mcp-hn
          env: {}
        source:
          name: registry
          entryId: 7f99f179-a459-4b32-b312-e03b383762fc
        disabled: false
      - name: custom-fetch
        transport:
          type: stdio
          command: uvx
          args:
            - mcp-server-fetch
        source:
          sourceName: registry
          sourceEntryId: 7f99f179-a459-4b32-b312-e03b383762fc
        disabled: false
      - name: notion
        transport:
          type: http
          url: https://mcp.notion.com/mcp
        toolPrefix: n_
  - id: prompts
    name: prompts
    servers: []
