name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: write
      packages: write
      pull-requests: write
      actions: read
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0
          # Use PAT to allow CI workflows to trigger on the created PRs
          token: ${{ secrets.GH_RELEASE_TOKEN }}
          persist-credentials: true

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install Dependencies
        run: bun install

      - name: Build packages
        run: bun run build

      - name: Create Release Pull Request or Publish packages
        id: changesets
        uses: changesets/action@v1
        with:
          publish: bun run release-packages
          version: bun run version-packages-formatted
          commit: "chore: release packages"
          title: "chore: release packages"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_RELEASE_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Build and publish Docker image
        if: steps.changesets.outputs.published == 'true'
        run: |
          cd apps/docker
          
          # Extract version from apps/docker/package.json
          VERSION=$(node -p "require('./package.json').version")
          
          # Build Docker image
          docker build -t barnaby/director:$VERSION -t barnaby/director:latest .
          
          # Login to Docker Hub
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          
          # Push Docker images
          docker push barnaby/director:$VERSION
          docker push barnaby/director:latest